os.pullEvent = os.pullEventRaw





  shell.run("clear")
  term.setTextColor(colors.yellow)
  print('CoopOS Installer')
  term.setTextColor(colors.white)
  print('SYSTEM REBOOTING IN 5')
  sleep(1)
  shell.run("clear")
  term.setTextColor(colors.yellow)
  print('CoopOS Installer')
  term.setTextColor(colors.white)
  print('SYSTEM REBOOTING IN 4')
  sleep(1)
  shell.run("clear")
  term.setTextColor(colors.yellow)
  print('CoopOS Installer')
  term.setTextColor(colors.white)
  print('SYSTEM REBOOTING IN 3')
  sleep(1)
  shell.run("clear")
  term.setTextColor(colors.yellow)
  print('CoopOS Installer')
  term.setTextColor(colors.white)
  print('SYSTEM REBOOTING IN 2')
  sleep(1)
  shell.run("clear")
  term.setTextColor(colors.yellow)
  print('CoopOS Installer')
  term.setTextColor(colors.white)
  print('SYSTEM REBOOTING IN 1')
  sleep(1)
  --start animation
  shell.run("clear")
  term.setTextColor(colors.yellow)
  print('CoopOS Installer')
  term.setTextColor(colors.white)
  print('SYSTEM REBOOTING IN')
  sleep(.1)
  shell.run("clear")
  term.setTextColor(colors.yellow)
  print('CoopOS Installer')
  term.setTextColor(colors.white)
  print('SYSTEM REBOOTING I')
  sleep(.1)
  shell.run("clear")
  term.setTextColor(colors.yellow)
  print('CoopOS Installer')
  term.setTextColor(colors.white)
  print('SYSTEM REBOOTING')
  sleep(.1)
  shell.run("clear")
  term.setTextColor(colors.yellow)
  print('CoopOS Installer')
  term.setTextColor(colors.white)
  print('SYSTEMREBOOTING')
  sleep(.1)
  shell.run("clear")
  term.setTextColor(colors.yellow)
  print('CoopOS Installer')
  term.setTextColor(colors.white)
  print('SYSTEREBOOTING')
  sleep(.1)
  shell.run("clear")
  term.setTextColor(colors.yellow)
  print('CoopOS Installer')
  term.setTextColor(colors.white)
  print('SYSTREBOOTING')
  sleep(.1)
  shell.run("clear")
  term.setTextColor(colors.yellow)
  print('CoopOS Installer')
  term.setTextColor(colors.white)
  print('SYSREBOOTING')
  sleep(.1)
  shell.run("clear")
  term.setTextColor(colors.yellow)
  print('CoopOS Installer')
  term.setTextColor(colors.white)
  print('SYREBOOTING')
  sleep(.1)
  shell.run("clear")
  term.setTextColor(colors.yellow)
  print('CoopOS Installer')
  term.setTextColor(colors.white)
  print('SREBOOTING')
  sleep(.1)
  shell.run("clear")
  --end animation
  term.setTextColor(colors.yellow)
  print('CoopOS Installer')
  term.setTextColor(colors.white)
  print("REBOOTING")
  sleep(.89)
  --start "..." animation
  sleep(.3)
  shell.run("clear")
  term.setTextColor(colors.yellow)
  print('CoopOS Installer')
  term.setTextColor(colors.white)
  print('REBOOTING.')
  sleep(.3)
  shell.run("clear")
  term.setTextColor(colors.yellow)
  print('CoopOS Installer')
  term.setTextColor(colors.white)
  print('REBOOTING..')
  sleep(.3)
  shell.run("clear")
  term.setTextColor(colors.yellow)
  print('CoopOS Installer')
  term.setTextColor(colors.white)
  print('REBOOTING...')
  --end of "..." animation
  sleep(3)
  os.reboot()
